// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Ji1B6ITaNxK1yEF5MzvPBFJTOOD1QTA',
    appId: '1:1044472376645:web:54229546152b351266a22c',
    messagingSenderId: '1044472376645',
    projectId: 'saferide-48eab',
    authDomain: 'saferide-48eab.firebaseapp.com',
    storageBucket: 'saferide-48eab.firebasestorage.app',
    measurementId: 'G-Z8RP76KW4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxAkzndC275bJ_x3MyOZItwrluzt2UmVg',
    appId: '1:1044472376645:android:e496d9e22fdf0ab966a22c',
    messagingSenderId: '1044472376645',
    projectId: 'saferide-48eab',
    storageBucket: 'saferide-48eab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjf6TASF4nt_-q6Zpk_xRm2WrLiRH1w_8',
    appId: '1:1044472376645:ios:1bc5fe116129e2f866a22c',
    messagingSenderId: '1044472376645',
    projectId: 'saferide-48eab',
    storageBucket: 'saferide-48eab.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjf6TASF4nt_-q6Zpk_xRm2WrLiRH1w_8',
    appId: '1:1044472376645:ios:1bc5fe116129e2f866a22c',
    messagingSenderId: '1044472376645',
    projectId: 'saferide-48eab',
    storageBucket: 'saferide-48eab.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Ji1B6ITaNxK1yEF5MzvPBFJTOOD1QTA',
    appId: '1:1044472376645:web:adcc9935086a119966a22c',
    messagingSenderId: '1044472376645',
    projectId: 'saferide-48eab',
    authDomain: 'saferide-48eab.firebaseapp.com',
    storageBucket: 'saferide-48eab.firebasestorage.app',
    measurementId: 'G-8G2JXP77EG',
  );
}
